CUDA_VISIBLE_DEVICES=1 python3 src/train_vanilla.py \
    --model_name_or_path ~/Models/Meta-Llama-3-8B \
    --data_path ./data/alpaca_data.json \
    --bf16 True \
    --output_dir ./outputs-alpaca/llama-3-8B-alpaca-Vanilla \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 32 \
    --eval_strategy "no" \
    --save_strategy "epoch" \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --report_to tensorboard